### ISSUE TITLE
Input moment?

### ISSUE THREAD

**Issue by mzahana** [marcelinomalmeidan/px4_control#1]
Hi

Thanks for this package. I have a technical question. In the paper you referenced, the control inputs are total thrust force and moments. The calculation of the input moments requires the knowledge of the inertia matrix. How do you handle that in your implementation?

Thanks.

**Comment by marcelinomalmeidan** [comment]
@mzahana, the output of the position control loop is a thrust and a desired orientation.  Px4 has an awesome attitude controller, so this repository only uses the position control portion of the referenced paper, and we leave it up to Px4 for orientation control

**Comment by mzahana** [comment]
Makes sense. Thanks for the prompt reply :)
